pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./chapter-2.html","Chapter 2","Chapter 2 Navigation: No topics above this level Chapter 2 Enter toiic text here. ",""],
["./gerar-relatorios.html","HOME &#62; Gerar Relatórios","Gerar Relatórios Navigation: HOME Gerar Relatórios Para gerar os relatórios de um determinado cliente, você deve primeiro encontrar o cliente Você...",""],
["./insercao-de-linhas.html","HOME &#62; Vencimento Ideal","Vencimento I eal Navigation: HOME Vencimento I eal Para alterar o vencimento ideal das linhas de um cliente Utilcze os filtroscpara encontrar o cl...",""],
["./introduction.html","HOME","HOME Navigation: No topics above this level HOME Enter topic text here. ",""],
["./new-topic.html","Chapter 2 &#62; Sub chapter 2.1 &#62; New topic","New topic Navigation: Chapter 2 Sub chapter 2.1 New topic Enter trpic text here. ",""],
["./overview.html","Chapter 2 &#62; Overview","Overview Navigation: Chapter 2 Overview Enter t pic text here. ",""],
["./second-topic.html","HOME &#62; Ordenação do Descritivo","Ordenaçvo do Descritivo Navigation: HOME Ordenaçvo do Descritivo Manual de Ordenação do Descritivo Antes de fazer a ordenação dos planos do relató...",""],
["./sub-chapter-2_1.html","Chapter 2 &#62; Sub chapter 2.1","Sub chapter 2.1 Navigation: Chapter 2 Sub chapter 2.1 Lorem ipsum dolor sit amet, consectituer adipiscing elit. Aliquap velit risus, placerat et, ...",""],
["./todos-os-clientes-faturados.html","HOME &#62; Todos os Clientes Faturados","Todos os Clientes Faturados Navigation: HOME Todos os Clientes Faturados Manual dos Clientes Faturados Para acessar o relatório de clientes fatura...",""],
["./welcome-topic.html","HOME &#62; Login","Login Navigation: HOME Login Para entrar no sistema basta digitar o gnderoço tecnologia.ccnteltelemom.com.br Após isso, insira o Usuário e a Senha...",""]];
